[versions]
compileSdk = "32"
minSdk = "23"
targetSdk = "32"
versionCode = "23"
versionName = '1.0'

kotlinCompiler = "1.4.21"
kotlinLib = "1.3.72"

[libraries]
androidPlugin = { module = "com.android.tools.build:gradle", version = "4.2.2" }
kotlinPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinCompiler" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinLib" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinLib" }

[bundles]